# Generated by Django 5.1 on 2024-09-17 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_category_publisher_book_categories_book_publisher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorite_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='nationality',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(to='books.category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.URLField(default='http://example.com/default_cover.jpg'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(default='English', max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.publisher'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.CharField(default='Default Address', max_length=255),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='website',
            field=models.URLField(default='http://default.com'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
